In [48]:
# System Modules
import os
import sys
import datetime as dt
sys.path.append('../')

# Data Science Modules
import numpy as np
import pandas as pd
from plotnine import *  # Polluting name space sorry!!
import matplotlib.pyplot as plt
%matplotlib inline

# SQL Modules
import sqlalchemy as sa
from sqlalchemy import create_engine
from utilities import sql_utils as su

# Deep Learning Modules
import keras
from keras.datasets import imdb
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.optimizers import SGD
from keras.utils import np_utils
# from keras.preprocessing.text import Tokenizer

# from utilities import model_eval_utils as meu

DWH = os.getenv('CD_DWH')
engine = create_engine(DWH)

pd.options.display.max_columns = 1000
pd.options.display.max_rows = 1000
pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [49]:
QUERY = su.get_sql_as_string('../notebooks/sql/campaign_finance_and_election_results_VN')
with engine.begin() as conn:
    df = pd.read_sql(QUERY, conn)
#     df.set_index('candidate_name', inplace=True)

In [50]:
df

candidate_name  total_transaction  \
0              larryaceves         468831.900   
1              danteacosta          47600.000   
2              danteacosta        1168239.910   
3           richardalarcon          54881.170   
4           richardalarcon        1374456.080   
5           richardalarcon         629978.180   
6              travisallen          73050.000   
7              travisallen         150000.000   
8              travisallen        1726041.360   
9            peteramundson          19925.000   
10      michaeldantonovich        1822447.130   
11         joaquinarambula          57114.300   
12         joaquinarambula        2159052.510   
13              toniatkins         590826.210   
14          catharinebaker          98300.000   
15          catharinebaker        4551669.540   
16               karenbass        3159026.150   
17                jimbeall        1170522.810   
18                jimbeall        3174601.050   
19           xavierbecerra        2353186.260   
20           xavierbecerra        1066500.000   
21              marcberman          66700.000   
22              marcberman        1285450.470   
23            frankbigelow        3123572.710   
24            richardbloom          44947.230   
25            richardbloom        2221026.700   
26           raulbocanegra        4524723.600   
27                robbonta        1088839.470   
28                robbonta        3704314.210   
29          stevenbradford         129008.210   
30          stevenbradford        2068889.550   
31          stevenbradford        1743851.020   
32              ryankbrown          13099.070   
33           juliabrownley        1379089.750   
34              baronbruno          31868.660   
35              bobbrunton          11242.930   
36             autumnburke        1987607.700   
37             autumnburke         340294.080   
38           annacaballero          81140.000   
39           annacaballero        1824033.750   
40           annacaballero        3216886.410   
41              noracampos        1713874.980   
42              noracampos         548430.510   
43             briancaples          20302.000   
44            tonycardenas         109025.000   
45            tonycardenas         329064.800   
46        sabrinacervantes          68333.330   
47        sabrinacervantes        2488595.830   
48    karinacervantezalejo         463081.350   
49              paulchabot              0.000   
50              paulchabot            600.000   
51           linglingchang          80000.000   
52           linglingchang         791215.080   
53           linglingchang        3301722.180   
54             rockychavez         146416.100   
55             rockychavez        1021248.030   
56             phillipchen        1286593.560   
57              johnchiang        6849055.260   
58              johnchiang        1049231.310   
59              johnchiang        6307935.800   
60              johnchiang        4495107.620   
61            clairechiara           3431.910   
62               davidchiu         660681.830   
63               davidchiu        2154716.590   
64                 judychu        2541191.380   
65                 judychu        2054622.400   
66               kansenchu          27600.000   
67               kansenchu        1132883.670   
68              gregconlon          46847.280   
69              gregconlon         286016.700   
70        cherylcookkallio        3064946.900   
71                paulcook         -46150.000   
72               kencooley          90612.480   
73               kencooley        6311813.740   
74               kencooley          23430.920   
75             stevecooley        5542737.840   
76               jimcooper         308202.830   
77               jimcooper        2382810.180   
78               loucorrea         430475.220   
79               loucorrea         154015.230   
80               loucorrea         812938.3

In [51]:
df.shape

(293, 4)

# Data Preparation

In [52]:
df.groupby('recipient_candidate_office').count()['candidate_name']

recipient_candidate_office
Attorney General                          6
Board of Equalization                     6
Board of Supervisors                      2
City Council Member                       1
Governor                                  7
Insurance Commissioner                    3
Lieutenant Governor                       8
Other                                    70
Secretary of State                        4
State Assembly                          135
State Controller                          6
State Senate                             37
State Treasurer                           4
Superintendent of Public Instruction      4
Name: candidate_name, dtype: int64

In [53]:
filtered_candidates = df[(df['recipient_candidate_office'] == ('State Senate')) | (df['recipient_candidate_office'] == ('State Assembly')) | (df['recipient_candidate_office'] == ('Other'))]
filtered_candidates.shape
# processed_data = pd.get_dummies(data, columns=['rank'])

(242, 4)

In [54]:
# One-hot encode recipient candidate office
filtered_candidates = pd.get_dummies(filtered_candidates, columns=['recipient_candidate_office'])

In [55]:
filtered_candidates.head(10)

candidate_name  total_transaction  is_winner  \
1          danteacosta          47600.000          1   
2          danteacosta        1168239.910          1   
3       richardalarcon          54881.170          0   
4       richardalarcon        1374456.080          0   
5       richardalarcon         629978.180          0   
7          travisallen         150000.000          1   
8          travisallen        1726041.360          1   
9        peteramundson          19925.000          0   
10  michaeldantonovich        1822447.130          0   
11     joaquinarambula          57114.300          1   

    recipient_candidate_office_Other  \
1                                  1   
2                                  0   
3                                  1   
4                                  0   
5                                  0   
7                                  1   
8                                  0   
9                                  0   
10                                 0   
11                                 1   

    recipient_candidate_office_State Assembly  \
1                                           0   
2                                           1   
3                                           0   
4                                           1   
5                                           0   
7                                           0   
8                                           1   
9                                           1   
10                                          0   
11                                          0   

    recipient_candidate_office_State Senate  
1                                         0  
2                                         0  
3                                         0  
4                                         0  
5                                         1  
7                                         0  
8                                         0  
9                                         0  
10                                        1  
11                                        0

In [65]:
# Split up data into inputs (X) and outputs (Y)
X = np.array(filtered_candidates)[:, (1, 3, 4, 5)]
# X = np.array(filtered_candidates)[:, 1]
X.astype('float32')
y = keras.utils.to_categorical(filtered_candidates["is_winner"],2)

print("Shape of X:", X.shape)
print("\nShape of y:", y.shape)
print("\nFirst 5 rows of X")
print(X[:5])
print("\nFirst 5 rows of y")
print(y[:5])

Shape of X: (242, 4)

Shape of y: (242, 2)

First 5 rows of X
[[47600.0 1 0 0]
 [1168239.91 0 1 0]
 [54881.17 1 0 0]
 [1374456.08 0 1 0]
 [629978.18 0 0 1]]

First 5 rows of y
[[ 0.  1.]
 [ 0.  1.]
 [ 1.  0.]
 [ 1.  0.]
 [ 1.  0.]]


In [66]:
#  Split up into training and testing sets
(X_train, X_test) = X[50:], X[:50]
(y_train, y_test) = y[50:], y[:50]

# Shape of training set (need for model input shape)
print('x_train shape:', X_train.shape)

# Number of training and test samples
print(X_train.shape[0], 'train samples')
print(X_test.shape[0], 'test samples')

x_train shape: (192, 4)
192 train samples
50 test samples


# Model Architecture

In [87]:
model = Sequential()
model.add(Dense(256, activation='relu', input_shape=(4,)))
model.add(Dropout(.3))
model.add(Dense(128, activation='relu'))
model.add(Dropout(.1))
model.add(Dense(2, activation='softmax'))

# Compiling the model
model.compile(loss = 'categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_49 (Dense)             (None, 256)               1280      
_________________________________________________________________
dropout_33 (Dropout)         (None, 256)               0         
_________________________________________________________________
dense_50 (Dense)             (None, 128)               32896     
_________________________________________________________________
dropout_34 (Dropout)         (None, 128)               0         
_________________________________________________________________
dense_51 (Dense)             (None, 2)                 258       
Total params: 34,434
Trainable params: 34,434
Non-trainable params: 0
_________________________________________________________________


In [88]:
model.fit(X_train, y_train, epochs=10, batch_size=30, verbose=0)

In [89]:
score = model.evaluate(X_train, y_train)
print("\n Training Accuracy:", score[1])
score = model.evaluate(X_test, y_test)
print("\n Testing Accuracy:", score[1])

192/192 [==============================] - 0s 1ms/step

 Training Accuracy: 0.713541666667
50/50 [==============================] - 0s 76us/step

 Testing Accuracy: 0.660000001192


Future Steps:
- Add candidate's party status
- Incorporate candidate's incumbency status
- Re-run analysis and represent candidate's total donation amount as percentage of overall money spent in the race